---
jupyter:
  jupytext:
    formats: Rmd,ipynb
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# What is a slope?

The graph below shows the x axis, the y axis and the origin. Any point on the graph can be specified by an x coordinate and a y coordinate. For instance, the origin is the point where x = 0 and y = 0. 

Note: theoretically these axes (and all the lines we will plot on them) run infinitely in the directions they travel in. However, as your screen isn't infinite, they are truncated for the purpose of display).

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import pandas as pd
plt.figure(figsize = (8,8))
x_axis = np.arange(-10, 11)
y_axis = np.arange(-10, 11)
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, 1))
plt.legend()
plt.show()
```

(Note: you may be more familiar with seeing the numbers appear on the axes, as in this picture: https://www.maplesoft.com/support/help/content/2092/ecplot162.gif ;
The graphs we will plot show the numbers on the side of the figure,  rather than on the axes themselves. This shows the same information, just in a different way.)

These axes provide us a way of visualising the relationship between two sets of data. Why is this important?:

<i> 'The dominant task of the human cortex is to extract visual information from the activity patterns on the retina. Our visual system is therefore exceedingly good at detecting patterns in visualized data sets. As a result, one can almost always see what is happening before it can be demonstrated through a quantitative analysis of the data. Visual data displays are also helpful at finding extreme data values, which are often caused by [...] mistakes in the data acquisition.' (p.51, Haslwanter, T., 2016, An Introduction to Statistics with Python) </i>

Let's plot the point (x = 5, y = 5), it is shown as a red 'x' on the graph below:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
plt.figure(figsize = (8,8))
x_axis = np.arange(-10, 11)
y_axis = np.arange(-10, 11)
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.plot(5,5, 'x', color = 'darkred', markersize = 8, label = '(x = 5, y = 5)')
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, 1))
plt.legend()
plt.show()
```

In a sense, the simplest line we can draw is one where, for any point on the line, the x and y coordinate are the same number. 

So when x = 0 then y = 0,

when x = 1 then y = 1, 

when x = 5 then y = 5, 

when x = 10 then y = 10 and so on.

The equation for this line is ```y = x```, and this line is shown in red below.

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
x = np.arange(-8, 9)
y = x
plt.figure(figsize = (8,8))
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(5,5, 'x', color = 'darkred', markersize = 8, label = '(x = 5, y = 5)')
plt.plot(x,y, color = 'red', label = 'y = x')
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, 1))
plt.legend()
plt.show()
```

You'll notice that the point (x = 5, y = 5) is on this line. A line can be thought of as a collection of infinitely close points. The equation for a line - in this case ```y = x``` - tells you which points are on the line. 

If we know the equation for the line, we can work out which points are on the line by taking any value of x and, using the equation, work out the y coordinate for that value of x.

The table below shows the x and y coordinates for some of the points on the line ```y = x```. As you can see, whatever x equals, y equals the same number.

```{python}
df = pd.DataFrame({'x coordinate:': x, 'y coordinate:': y})
df.index = np.repeat('', len(df))
display(df)
```

Another way to write ```y = x``` is ```y = 1 * x```, as anything multiplied by 1 equals itself. 

What happens if we change that '1' in ```y = 1 * x``` to another number? Let's change that number from '1' to '5'. The graph below shows, in blue, the line for the equation ```y = 5 * x```. Our original line ```y = 1 * x``` is also shown, in red.

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y1 = 5*x
plt.figure(figsize = (8,8))
plt.plot(x,y, color = 'red', label = 'y = 1 * x')
plt.plot(x,y1, color = 'blue', label = 'y = 5 * x')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.ylim(min(y_axis), max(y_axis))
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, 1))
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.legend()
plt.show()
```

The number we have changed -  from '1' to '5' - is the <b> slope </b>. Graphically, we can see that changing the slope changes the steepness of the line : the line for ```y = 5 * x``` is much steeper than the line for ```y = 1 * x```.

What the slope tells us is this: for the x-coordinate of any point on the line, how much bigger/smaller is the y coordinate?

In the case of ```y = 1  * x```: 

where x = 1, y equals 1 times the value of x ... so y = 1,

where x = 5, y equals 1 times the value of x ... so y = 5 etc.

In the case of ```y = 5 * x```, y equals 5 times the value of x. So: 

where x = 1, y equals 5 times the value of x ... so y = 5,

where x = 5, y equals 5 times the value of x... so y = 25 etc.

The table below shows this for a set of points on the line ```y = 5 * x```:

```{python}
df = pd.DataFrame({'x coordinate:': x, 'y coordinate:': y1})
df.index = np.repeat('', len(df))
display(df)
```

Another way of thinking of this is: if we take any two points on the line, and we calculate how much the x-value has changed between those points, then the slope tells us how much the y value has also changed.

So for the line ```y = 1 * x```, if we follow the line from x = 0 to x = 5, the slope tells us how much the y values have changed over this distance. 

The graph below shows that, for the line ```y = 1 * x```, as x changes from 0 to 5, y also changes from 0 to 5.

(This graph shows slightly more of the x and y axes than the previous graphs, as we will need this for the line we plot after this one).

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
plt.figure(figsize = (8,8))
y_axis_ext = np.arange(-30, 31)
x_axis_ext = np.arange(-30, 31)
plt.plot(x_axis_ext , np.repeat(0, len(x_axis_ext)), color = 'black')
plt.plot(np.repeat(0, len(y_axis_ext)), y_axis_ext, color = 'black')
plt.plot(x,y, color = 'red', label = 'y = 1 * x')
plt.plot([5, 0, 5], [5,5, 0], 'x', color = 'black')
zer_5 = np.arange(0,6)
plt.plot(np.repeat(5, len(zer_5)), zer_5, '--', color = 'darkgreen', label = 'Change in y')
plt.plot(zer_5, np.repeat(5, len(zer_5)),'--', color = 'cyan', label = 'Change in x')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.ylim(min(y_axis_ext), max(y_axis_ext))
plt.xlim(min(x_axis_ext), max(x_axis_ext))
plt.xticks(np.arange(np.min(x_axis_ext), np.max(x_axis_ext)+1, 5))
plt.yticks(np.arange(np.min(y_axis_ext), np.max(y_axis_ext)+1, 5))
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.legend()
plt.show()
```

The graph below shows the same change in x (from 0 to 5) for the line ```y = 5 * x```.

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
plt.figure(figsize = (8,8))
plt.plot(x_axis_ext , np.repeat(0, len(x_axis_ext)), color = 'black')
plt.plot(np.repeat(0, len(y_axis_ext)), y_axis_ext, color = 'black')
plt.plot([5, 0, 5], [25,25, 0], 'x', color = 'black')
plt.plot(x,y, color = 'red', label = 'y = 1 * x')
plt.plot(x,y1, color = 'blue', label = 'y = 5 * x')
zer_25 = np.arange(0,26)
plt.plot(np.repeat(5, len(zer_25)), zer_25, '--', color = 'darkgreen', label = 'Change in y')
plt.plot(zer_5, np.repeat(25, len(zer_5)),'--', color = 'cyan', label = 'Change in x')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.ylim(min(y_axis_ext), max(y_axis_ext))
plt.xlim(min(x_axis_ext), max(x_axis_ext))
plt.xticks(np.arange(np.min(x_axis_ext), np.max(x_axis_ext)+1, 5))
plt.yticks(np.arange(np.min(y_axis_ext), np.max(y_axis_ext)+1, 5))
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.legend()
plt.show()
```

If you compare the two graphs, you can see that, relative to the line ```y = 1 * x```, on the line ```y = 5 * x``` the value of y has changed a lot more for the same 5 point increase in x. It has changed by 5 times the amount. This may be clearer in the graph below:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
plt.figure(figsize = (8,8))
plt.plot(x,y, color = 'red', label = 'y = 1 * x')
plt.plot(x,y1, color = 'blue', label = 'y = 5 * x')
plt.plot(x_axis_ext , np.repeat(0, len(x_axis_ext)), color = 'black')
plt.plot(np.repeat(0, len(y_axis_ext)), y_axis_ext, color = 'black')
plt.plot([5, 0, 5], [25,25, 0], 'x', color = 'black')
plt.plot([5, 0, 5], [5,5, 0], 'x', color = 'black')
zer_25 = np.arange(0,26)
plt.plot(np.repeat(5, len(zer_25)), zer_25, '--', color = 'darkgreen', label = 'Change in y')
plt.plot(zer_5, np.repeat(25, len(zer_5)),'--', color = 'cyan', label = 'Change in x')
plt.plot(np.repeat(5, len(zer_5)), zer_5, '--', color = 'darkgreen')
plt.plot(zer_5, np.repeat(5, len(zer_5)),'--', color = 'cyan')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.ylim(min(y_axis_ext), max(y_axis_ext))
plt.xlim(min(x_axis_ext), max(x_axis_ext))
plt.xticks(np.arange(np.min(x_axis_ext), np.max(x_axis_ext)+1, 5))
plt.yticks(np.arange(np.min(y_axis_ext), np.max(y_axis_ext)+1, 5))
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.legend()
plt.show()
```

The change in x is the same for each line, but the change in y is much larger for the line with the larger slope, ```y = 5 * x```.

The larger the slope, the larger the change in y for a change in x. In this case, for the line ```y = 5 * x```, as the line moves 5 points along the x axis, it moves 5 times that amount (25 points) along the y axis. 

Conversely, for the line ```y = 1 * x```, as the line moves 5 points along the x axis, it only moves 5 points along the y axis.

What would the graph look like if we change the slope of the line to 10, instead of 1? This new line, ```y = 10 * x```, is shown below, in green.

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y2 = 10*x
plt.figure(figsize = (8,8))
plt.plot(x,y, color = 'red', label = 'y = 1 * x')
plt.plot(x,y1, color = 'blue', label = 'y = 5 * x')
plt.plot(x,y2, color = 'green', label = 'y = 10 * x')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis_ext)), y_axis_ext, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.ylim(min(y_axis_ext), max(y_axis_ext))
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis_ext), np.max(y_axis_ext)+1, 5))
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.legend()
plt.show()
```

As you can see, the take-home message is that if we increase the slope, the line gets steeper.

For lines with positive slopes, when the values of x are negative, the values of y are also negative. And when the values of x are positive, the values of y are also positive. Look at the graph above to confirm this is correct.

But what about if we make the slope negative? 

Let's try making the slope -5. The line for ```y = -5 * x``` is shown below, as a dashed line in dark blue. For comparison, the line ```y = 5 * x``` is also shown, as a solid line in lighter blue.

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y3 = -5 * x
plt.figure(figsize = (8,8))
plt.plot(x,y1, color = 'blue', label = 'y = 5 * x')
plt.plot(x, y3, '--', color = 'darkblue', label = 'y = -5 * x')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.ylim(min(y_axis), max(y_axis))
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, 1))
plt.legend()
plt.show()
```

As you can see, the lines are equally steep. However, for the line with the negative slope, when the x values are negative, the y values are positive. And when the x values are positive, the y values are negative. 

So changing the sign of the slope (from positive 5 to negative 5) has reversed the direction the line travels in. But the steepness of the line is the same.

The graph below shows multiple lines, so that you can see the relationship between the size of the slope (large or small), and the sign of the slope (positive or negative - lines with negative slopes are shown as dashed lines).

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y4 = -x
y6 = -10 *x
plt.figure(figsize = (8,8))
plt.plot(x,y, color = 'red', label = 'y = 1 * x')
plt.plot(x,y2, color = 'green', label = 'y = 10 * x')
plt.plot(x,y4, '--', color = 'darkred', label = 'y = -1 * x')
plt.plot(x, y6,'--',  color = 'darkgreen', label = 'y = -10 * x')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.ylim(min(y_axis), max(y_axis))
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, 1))
plt.legend()
plt.show()
```

# What is an intercept?

Look at the graph above. Despite having different sizes of slope, with different signs, all of the lines pass through the origin at (x = 0, y = 0).

The <b>intercept</b> is the term for where a line crosses the y axis. The intercept for all the lines in the above graph is 0, as they all cross the y axis where y = 0. 

We can change the intercept of a line by adding or subtracting a quantity in the equation for the line. This has the effect of adding or subtracting that quantity from every point on the line. This is easier to illustrate graphically.

The graph below shows two lines. One we have seen before, ```y = 1 * x``` (shown in blue), and a new line ```y = 1 * x + 5``` (shown in gold).

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y1 = x
y2 = x + 5
plt.figure(figsize = (8,8))
plt.plot(x,y1, color = 'blue', label = 'y = 1 * x')
plt.plot(x,y2, color = 'gold', label = 'y = 1 * x + 5')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.ylim(min(y_axis), max(y_axis))
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, 1))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, 1))
plt.legend()
plt.show()
```

We can see that the new line, ```y = 1 * x + 5```, crosses the y axis at 5, but the steepness of the line is the same as ```y = 1 * x``` - it is only the point that each line crosses the y axis that is different.

For any value of x on the line ```y = 1 * x + 5```, the y value equals 1 times the x value, plus the intercept, which in this case is 5. 

So if x = 0, y equals 1 times the value of x, plus the intercept: so y = 0 + 5 = 5. 

If x = 2, y equals 1 times the value of x, plus the intercept: so y = 2 + 5 = 7 etc.

That's all there is to it. Adding or subtracting an intercept from a line simply moves the line up and down the y axis. If the rest of the equation is the same, that is all that changes. This is true regardless of what the slope is:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y1 = 10 * x
y2 = 10 * x + 5
plt.figure(figsize = (8,8))
plt.plot(x,y1, color = 'blue', label = 'y = 10 * x')
plt.plot(x,y2, color = 'gold', label = 'y = 10 * x + 5')
y_axis = np.arange(-20, 21)
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.ylim(min(y_axis), max(y_axis))
plt.legend()
plt.show()
```

Let's see what happens if we set the intercept to -5, rather than postive 5:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y1 = 5 * x
y2 = 5 *  x + 5
y3 = 5 *  x - 5
plt.figure(figsize = (8,8))
plt.plot(x,y1, color = 'orange', label = 'y =  5 * x')
plt.plot(x,y2, color = 'crimson', label = 'y = 5 * x + 5')
plt.plot(x,y3, color = 'darkred', label = 'y = 5 * x - 5')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.ylim(min(y_axis), max(y_axis))
plt.legend()
plt.show()
```

You can see that a negative intercept moves the line downwards away from the origin. 

A positive intercept moves the line upwards away from the origin.

This is also true if the slope is negative, as can be seen from the graph below:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
y1 = -5 * x
y2 = -5 *  x + 5
y3= -5 *  x - 5
plt.figure(figsize = (8,8))
plt.plot(x,y1,'--', color = 'darkblue',  label = 'y =  -5 * x')
plt.plot(x,y2,'--', color = 'silver',  label = 'y = -5 * x + 5')
plt.plot(x,y3, '--',color = 'darkred',  label = 'y = -5 * x - 5')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.ylim(min(y_axis), max(y_axis))
plt.legend()
plt.show()
```

### In summary: the slope determines the steepness of the line. The intercept moves the line up and down the y axis, relative to the origin.


# Why do we care?

Fitting a line to a set of datapoints can be used for description and prediction.

The graph below shows some simulated data, where each point represents one person with a disease. 

The x-coordinate of the point shows that person's pre-treatment symptom severity score (out of 100). And the y-coordinate of the point shows the dose of a drug (in micrograms) that was most effective for treating that person:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
samp_size = 30
symptom_severity = np.random.normal(67, 10,  size = samp_size).astype('int')
symptom_severity[symptom_severity > 100] = 100
most_effect_dose = 50 + 1.4 * symptom_severity + np.random.normal(0, 5, size = samp_size)
plt.figure(figsize = (10,6))
plt.scatter(symptom_severity, most_effect_dose)
plt.xlabel('Symptom Severity')
plt.ylabel('Most Effective Dose')
plt.show()
```

We can fit a line to this data by using mathematical techniques which find the equation for the line which minimizes the collective distance between the datapoints and the line.

Fitting a line can help us describe the strength and direction of the relationship between initial symptom severity and the most effective dose:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
lin_reg = scipy.stats.linregress(symptom_severity, most_effect_dose)
slope = lin_reg[0]
intercept = lin_reg[1]
ols_line = intercept  + slope * symptom_severity
plt.figure(figsize = (10,6))
plt.scatter(symptom_severity, most_effect_dose)
plt.xlabel('Symptom Severity')
plt.ylabel('Most Effective Dose')
plt.plot(symptom_severity, ols_line, color = 'darkred', label = 'Best-fitting straight line:  y = '+str(np.round(slope,2))+' * x + '+str(np.round(intercept, 2)))
plt.legend()
plt.show()
print('The equation for the best-fitting straight line is:')
print('\ny = ', np.round(slope,2), '* x + ', np.round(intercept, 2))
print('\n(Remember that in this case "x" is the symptom severity score!)\n')
print(np.round(slope,2), 'is the slope.')
print(np.round(intercept,2), 'is the intercept.')
```

The steeper the slope of the best fitting line, the stronger the relationship between the two variables. The intercept is important too, we will explain why shortly.

Once we have fitted a line, we can use it to predict things.

In this hypothetical example, if we had a new patient, we could use their initial symptom severity score to predict which dose will be most effective for them, based on what we have observed in the previous patients.

It is important to have good predictions in this case: if the dose is too low, the treatment will be ineffective. If the dose is too high, there will be more side effects.

The graph below shows how we would use an initial symptom severity score (for instance, of 70) to predict the most effective dose for that patient. We would do this by checking what the y coordinate is for the point on the line where x = 70:

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
predict_70 = intercept + slope * 70
plt.figure(figsize = (10,6))
plt.scatter(symptom_severity, most_effect_dose)
plt.xlabel('Symptom Severity')
plt.ylabel('Most Effective Dose')
plt.plot(symptom_severity, ols_line, color = 'darkred', label = 'Best-fitting straight line:  y = '+str(np.round(slope,2))+' * x + '+str(np.round(intercept, 2)))
plt.plot(70, predict_70, 'X', markersize = 15, color = 'red', label = 'Predicted best dose for symptom severity = 70' )
plt.yticks(np.arange(np.min(most_effect_dose).astype('int'), np.max(most_effect_dose)+1, 5))
plt.legend()
plt.show()
print('In this example, the predicted most effective dose (for a symptom severity score of 70) is '+str(np.round(predict_70,2))+', as this is the y-coordinate for the point on the line where x = 70.')
print('\nLook at the y-axis level with the red "x" to see that this is correct.')
```

The graph below shows the same prediction, but also shows the origin.

Remember that all lines pass through the origin if they do not have a nonzero intercept (i.e. an intercept that is any other number apart from 0). 

So, we need a nonzero intercept - that is, we need to add or subtract a quantity from every value on the line - if the line which best fits the data does not pass through the origin. 

In our current example, without the nonzero intercept, our line would not pass through the data.

With an intercept of 0, the line would have the correct slope, but it would be too low down the y axis to make useful predictions. 

The graph below shows a green line which has the same slope as the best fitting line, but has an intercept of 0. You can see that it does not fit the data well at all. If we use that line to make predictions, they would be very inaccurate.

```{python}
# do not worry about any of the code in this notebook, it is just here to generate the graphs
predict_70 = intercept + slope * 70
bad_line = slope*symptom_severity
plt.figure(figsize = (14,10))
plt.scatter(symptom_severity, most_effect_dose)
plt.xlabel('Symptom Severity')
plt.ylabel('Most Effective Dose')
plt.plot(symptom_severity, ols_line, color = 'darkred', label = 'Best-fitting straight line:  y = '+str(np.round(slope,2))+' * x + '+str(np.round(intercept, 2)))
plt.plot(symptom_severity, bad_line,  color = 'green', label = 'Line with the correct slope, but a 0 intercept: y = '+str(np.round(slope,2))+' * x + 0')
plt.plot(70, predict_70, 'X', markersize = 15, color = 'red', label = 'Predicted best dose, for symptom severity = 70' )
y_axis = np.arange(-np.max(most_effect_dose), np.max(most_effect_dose))
x_axis = np.arange(-np.max(symptom_severity), np.max(symptom_severity))
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
zer_to_pred = np.arange(0,predict_70)
zer_to_70 = np.arange(0,70)
plt.plot(np.repeat(70, len(zer_to_pred)), zer_to_pred, '--', color = 'darkred')
plt.plot(zer_to_70, np.repeat(predict_70, len(zer_to_70)),'--', color = 'darkred')
plt.legend()
plt.show()

```

# Try it yourself

If you are using an interactive version of this notebook, try changing the values of the slope and intercept in the cell below, and then running the cell, to plot your own lines:

```{python}
# change the values of the slope and intercept below

slope = 1

intercept = 0


# do not alter the code below this point

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import pandas as pd

plt.figure(figsize = (14,10))
x = np.arange(-10, 11)
y = slope * x + intercept
plt.plot(x, y, label = 'y = '+str(slope)+' * x + '+str(intercept))
biggest_abs_x = np.max(np.abs([np.min(x), np.max(x)]))
biggest_abs_y = np.max(np.abs([np.min(y), np.max(y)]))
x_axis = np.arange(-biggest_abs_x, biggest_abs_x+1)
y_axis = np.arange(-biggest_abs_y , biggest_abs_y +1)
plt.plot(x_axis, np.repeat(0, len(x_axis)), color = 'black')
plt.plot(np.repeat(0, len(y_axis)), y_axis, color = 'black')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.plot(0,0, 'o', color = 'black', markersize = 8, label = 'The Origin (x = 0, y = 0)')

max_x_axis = np.max(x_axis)
if max_x_axis == 0:
    max_x_axis = max_x_axis + 0.05
    
max_y_axis = np.max(y_axis)
if max_y_axis == 0:
    max_y_axis = max_y_axis + 0.05
    
plt.xticks(np.arange(np.min(x_axis), np.max(x_axis)+1, max_x_axis/10))
plt.yticks(np.arange(np.min(y_axis), np.max(y_axis)+1, max_y_axis/10))
plt.legend()
plt.show()
```

```{python}

```
