---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.5
---

# Boolean arrays

## Select values with Boolean arrays

Here we are using Boolean arrays to *index* into other arrays.  You will see what we mean by that by the end of this section.

We often want to select several elements from an array according to some
criterion.

The most common way to do this, is to do array slicing, using
a Boolean array between the square brackets.

It can be easier to understand this by example than by description.


Remember [the RateMyProfessors dataset](../data/rate_my_professors).

It it a table where the rows are academic disciplines, and the columns contain the average student rating values for the corresponding discipline.

If you are running on your laptop, you should download the
{download}`rate_my_course.csv <../data/rate_my_course.csv>` file to the same
directory as this notebook.

```{python}
# We have not covered this code yet.  We will soon.
# Load the library for reading data files.
import pandas as pd
# Read the file, select the first 10 values.
big_courses = pd.read_csv('rate_my_course.csv').head(10)
# Put the columns into arrays
disciplines = big_courses['Discipline'].values
easiness = big_courses['Easiness'].values
quality = big_courses['Overall Quality'].values
```

We now have the names of the disciplines with the largest number of professors.

```{python}
disciplines
```

Here are the "Overall Quality" scores for the ten largest courses:

```{python}
quality
```

These are the quality ratings corresponding to the `disciplines` we saw earlier.  The top (largest) discipline is:

```{python}
disciplines[0]
```

The Overall Quality rating for that course is:

```{python}
quality[0]
```

## Boolean arrays

Boolean arrays are arrays that contain values that are one of True or False.

Here is a Boolean array, created from applying a comparison to an array:

```{python}
greater_than_3 = easiness > 3
greater_than_3
```

This has a `True` value at the positions of elements > 3, and `False`
otherwise.


We can do things like count the number of `True` values in the Boolean array:

```{python}
np.count_nonzero(greater_than_3)
```

Now let us say that we wanted to get the elements from `easiness`
that are greater than 4.   That is, we want to get the elements
in `easiness` for which the corresponding element in
`greater_than_3` is `True`.

We can do this with *Boolean array indexing*.  The Boolean array goes between the square brackets, like this:

```{python}
easiness
```

```{python}
greater_than_3
```

```{python}
easiness[greater_than_3]
```

We have selected the numbers in `easiness` that are greater than 3.


We can use this same Boolean array to index into another array.  For example, here we show the discipline *names* corresponding to the courses with Easiness scores greater than 3:

```{python}
disciplines[greater_than_3]
```

Just to confirm that these are the disciplines with "Easiness" ratings greater than 4, here are the first ten rows of the table.  These are the rows corresponding to numbers in the arrays.

```{python}
# We haven't covered '.head' yet.  This code shows the first 10 rows of
# the data table.
big_courses.head(10)
```

## Setting values with Boolean arrays

You have seen, above, that Boolean indexing can select values from an array:

```{python}
# Create the Boolean array
another_array = np.array([2, 3, 4, 2, 1, 5, 1, 0, 3])
are_gt_2 = another_array > 2
are_gt_2
```

```{python}
# Get the values by indexing with the Boolean array.
# Return only the values of 'another_array' where the Boolean array has True.
another_array[are_gt_2]
```

Given what you know, what do you think would happen with:

```
another_array[are_gt_2] = 10
another_array
```

Try it.
